version: '3'
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
